language: node_js
node_js:
- 10
- 12
- 13
script:
- yarn lint
- yarn report
env:
  global:
    secure: TjAp42TwVS/PTeo1a58jMQqjkWb+VilBGxUPCn7vLeEKyDAaW43v0qESMLwqZem1GyvpZm9UoxDEQpFcsiLk8YqbR9cQTDcibttVkaE7XO5bBYS9qHrETiCiYIHViM0jwekRUs5WOZRSRB1SFoGUExcjj3fU8WMy5u1kvBzEV6JAzKRPbyBxp883CylWW6Zg2FjQe5aEMisqxxc3VFSy6iilcS3Yk/DtaCGz9MuESEUEsud8UAWFMQwVIoZW259IceIutBoOyliLujVTNbAXv8CLhvtWH7NtWpG1Ui1J56UszVPqXjvx0RDsX7u6TzN7YQPh5XcGFEQc0NpMyQsGcxzFR8yXWBGcAms+A9NjpP+lBNU5a/Iwnn5ewn7dxTgxnuoEp/hhVXkLBfgTL+nP3x+uwv0EpSF05d29ObW7IP91rGTVv6vihjxVTXQNA4qNRzomMIu1x0Cc64rJqtL2z0brTZnEra/+UrreUVcCmlVp8KVtFcmNwLpOgR+PvSoP9edK901XXVXQD2wYE23jkdjV8lDTQ2s3PXdHm3cy+nfMzMoFm+FY8kl/SRdgOTkpoguizG9sgUqi/RQM6hn7Q/h3kz4h2eA4AbymGpQ8Uox0FQjudSX08gKy6g6jszQ3El/vZwBSZTWaB1uEcvKX6czcH1P8Dp9abB2w1wwcnfw=
